version: '3.8'

services:
  app:
    build: .
    container_name: llm-hf-exp-5
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - ./src:/app
